apiVersion: v1
kind: Secret
metadata:
  name: cb360secrets
  namespace: {{ .Values.app.namespace }}
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/argocd"
type: Opaque
stringData:
  postgres-password: password
